CREATE DATABASE METAL_DB;
USE METAL_DB;

CREATE TABLE METAL_MASTER(
    SLAB_NO VARCHAR(255) PRIMARY KEY,
    NEW_SLAB_NO VARCHAR(255),
    HEAT_NO VARCHAR(255),
    STEEL_GRADE VARCHAR(255),
    CAST_SEQUENCE_NO VARCHAR(255),
    SHIFT VARCHAR(255),
    STRAND_NO VARCHAR(255),
    DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NEW_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

    
CREATE TABLE METAL_DETAILS(
    ID SERIAL PRIMARY KEY,
    SLAB_NO VARCHAR(255),
    NEW_SLAB_NO VARCHAR(255),
    QTY_H DECIMAL(10,2),
	QTY_Al DECIMAL(10,2),
	QTY_B DECIMAL(10,2),
    QTY_Ga DECIMAL(10,2),
    QTY_In DECIMAL(10,2),
	QTY_Tl DECIMAL(10,2),
    FOREIGN KEY(SLAB_NO) REFERENCES METAL_MASTER(SLAB_NO));
